// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe-7LbO7e8KjzF8W4LL969VwkvGm0UYFk',
    appId: '1:282815998960:web:284ffc5358235ede060b35',
    messagingSenderId: '282815998960',
    projectId: 'csaf-md',
    authDomain: 'csaf-md.firebaseapp.com',
    storageBucket: 'csaf-md.appspot.com',
    measurementId: 'G-YLLHD2MMKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfJChAQtoCa5i3NaONHIjlE_GDGhuetJU',
    appId: '1:282815998960:android:276264026732bc16060b35',
    messagingSenderId: '282815998960',
    projectId: 'csaf-md',
    storageBucket: 'csaf-md.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiolR_S7H0T9elJqqE4CSMsqGZhJrd47M',
    appId: '1:282815998960:ios:197c4aaf4c7612ce060b35',
    messagingSenderId: '282815998960',
    projectId: 'csaf-md',
    storageBucket: 'csaf-md.appspot.com',
    iosClientId: '282815998960-jlqvfpk6v3ehl1uec5mleqoi6dgbba99.apps.googleusercontent.com',
    iosBundleId: 'com.userapps.csaf',
  );
}
